import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import bg from '../public/Mask.png'

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: "Desafio React",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        backgroundImage: `url(${bg.src})`,
        backgroundPosition: "bottom right",
        backgroundRepeat: "no-repeat",
        width: '100%',
        height: '100%',
      }} className={roboto.className}>{children}</body>
    </html>
  );
}
